import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Readme } from '../components/organisms/readme'
import { SearchForm } from '../components/organisms/search-form'
import { Commits } from '../components/organisms/commits'
import { useSearchQuery } from '../hooks/github-api'
import type { Commits as CommitsType } from '../models/commits'
import { useRouter } from 'next/router'
import { parseInputQuery } from '../lib/parse-input-query'
import { parseInputPage } from '../lib/parse-input-page'
import { ErrorMessage } from '../components/organisms/error-message'
import { Pagination } from '../components/organisms/pagination'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const { repository: rawInputQuery } = router.query
  const { owner, repository } = parseInputQuery(rawInputQuery)
  const { page } = parseInputPage(router.query.page)

  let commits: CommitsType | undefined
  let totalPage: number | undefined
  const { isInitialLoading, data, error, isError } = useSearchQuery({ owner, repository, page })

  if (data) {
    commits = data.commits
    totalPage = data.totalPage
  }

  return (
    <>
      <Head>
        <title>Commit Stalker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={`${inter.className} sticky top-0 bg-slate-50 z-30`}>
        <div className='flex items-center m-auto justify-around'>
          <h1 className='text-lg'>Commit Stalker</h1>
          <SearchForm owner={owner} repository={repository} page={page} />
        </div>
      </header>

      <main className={inter.className}>
        <div className='md:w-3/5 m-auto bg-white py-8 rounded'>
          {/* <SearchForm owner={owner} repository={repository} page={page} /> */}
          {!isError && isInitialLoading && <div>Loading...</div>}
          {!isInitialLoading && isError && <ErrorMessage>{String(error)}</ErrorMessage>}
          {totalPage && <Pagination count={totalPage} defaultPage={page} owner={owner} repository={repository} />}
          {commits && <Commits commits={commits} />}
          {totalPage && <Pagination count={totalPage} defaultPage={page} owner={owner} repository={repository} />}
        </div>
      </main>

      <footer className={`${inter.className} md:w-3/5 m-auto`}>
        <div>
          <Readme />
          <div className='py-4 text-center'>
            <a className='hover:underline'
              href='https://github.com/9sako6/commit-stalker'>9sako6/commit-stalker</a>
          </div>
        </div>
      </footer>
    </>
  )
}
