name: imgcmp
on: [pull_request]
jobs:
  imgcmp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: 9sako6/imgcmp@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
